

"Resource/UI/HudMedicCharge.res" 
{
"ChargeLabel" 
{
"ControlName" "CExLabel"
"fieldName" "ChargeLabel"
"xpos" "700"
"ypos" "414"
"zpos" "2"
"wide" "150"
"tall" "50"
"autoResize" "1"
"pinCorner" "2"
"visible" "1"
"enabled" "1"
"tabPosition" "0"
"labelText" "#TF_UberchargeMinHUD"
"textAlignment" "north-west"
"dulltext" "0"
"brighttext" "0"
"font" "TF2Build53"
"fgcolor" "QHUDChargeLabel"
}
"IndividualChargesLabel" 
{
"ControlName" "CExLabel"
"fieldName" "IndividualChargesLabel"
"xpos" "695"
"ypos" "415"
"zpos" "2"
"wide" "150"
"tall" "50"
"autoResize" "1"
"pinCorner" "2"
"visible" "1"
"enabled" "1"
"tabPosition" "0"
"labelText" "#TF_IndividualUberchargesMinHUD"
"textAlignment" "north-west"
"dulltext" "0"
"brighttext" "0"
"font" "TF2Build53"
"fgcolor" "255 255 255 255"
}
"ChargeMeter" 
{
"ControlName" "ContinuousProgressBar"
"fieldName" "ChargeMeter"
"font" "m0refont10"
"xpos" "475"
"ypos" "415"
"zpos" "1"
"wide" "74"
"tall" "6"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"textAlignment" "north-west"
"bgcolor_override" "QHUDChargeMeterBG"
"fgcolor_override" "QHUDChargeMeterFG"
"dulltext" "0"
"brighttext" "0"
}
"ResistIcon" 
{
"ControlName" "ImagePanel"
"fieldName" "ResistIcon"
"xpos" "0"
"ypos" "0"
"wide" "0"
"tall" "0"
"visible" "0"
"enabled" "0"
"image" "../HUD/defense_buff_bullet_blue"
"scaleImage" "1"
}
}
